### ISSUE TITLE
Running Requirements ?

### ISSUE THREAD

**Issue by Greatz08** [huanngzh/MV-Adapter#5]
it is looking pretty good project imo so thanks for sharing it with others :-) , i was wondering what are system requirements for running this model to generate images ?

**Comment by huanngzh** [comment]
We have just updated the system requirements in [README](https://github.com/huanngzh/MV-Adapter?tab=readme-ov-file#system-requirements). We recommend running MV-Adapter in RTX 3090/4090. In the model zoo of MV-Adapter, running image-to-multiview generation has the highest system requirements, which requires about 14G GPU memory.

**Comment by nicoptere** [comment]
the text to image script (`MV-Adapter\scripts\inference_t2mv_sdxl.py`) works on a RTX 2080 Ti with 11Go RAM but goes OOM if `num_views` goes beyond 12.

**Comment by huanngzh** [comment]
> the text to image script (`MV-Adapter\scripts\inference_t2mv_sdxl.py`) works on a RTX 2080 Ti with 11Go RAM but goes OOM if `num_views` goes beyond 12.

Yep, generating more views will need larger RAM.
