### ISSUE TITLE
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.

### ISSUE THREAD

**Issue by sasori7** [huanngzh/MV-Adapter#9]
I'm getting lots of these.
Is the image going to get rendered eventually, or is my system now just spinning it's wheels?

**Comment by huanngzh** [comment]
This warning is caused by `diffusers`, but it does not affect the results. We will try to submit a PR to diffusers to avoid this warning interference.
